resources:
- name: pbd-hackday-ci
  type: git
  icon: github
  source:
    uri: https://github.com/hmrc/pbd-hackday-ci

jobs:
- name: build-and-test
  plan:
  - get: pbd-hackday-ci
  - task: build-the-docker-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
        - name: pbd-hackday-ci
      params:
        CONTEXT: pbd-hackday-ci/concourse/test-image
        UNPACK_ROOTFS: true
      run:
        path: build
      outputs:
        - name: image
  - task: test-the-docker-image
    image: image
    config:
      platform: linux
      run:
        path: cat
        args: ["/test-file.txt"]
